# Generated by Django 5.2.1 on 2025-05-14 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
